experiments:
  shared:
    script: shared_train.py
    epochs: 25
    learning_rate: 0.5

  specialized:
    script: special_train.py
    epochs: 10
    description: "Specialized experiment"

datasets:
  common_set:
    root: /data/common
    experiments:
      - name: shared

  custom_set:
    root: /data/custom
    description: "Custom set of data"
    experiments:
      - name: shared
        override:
          learning_rate: 0.01
      - name: specialized
        output_vars: [class1]